TwiN/gatus

README.md, core/condition.go, core/condition_test.go, core/service.go, core/types.go
=> Add certificate expiration support

.dockerignore, Dockerfile
improving build caching, use COPY instead of ADD
- adding `Dockerfile` and `.git/` to `.dockeringore` improves
caching when building images when these paths have changes
unrelated to application functionality
- using COPY instead of ADD, since working with local paths, and
not extracting archived data
- installing packages before building application binary improves caching,
and avoids installing packages every time the application code changes
=> Misc improvements

.gitignore, README.md, config/config.go, config/config_test.go, main.go
Host and port can be specified by either a environment variable or a
dedicated command line parameter. Command line parameters will be preferred
over environment variables, which will be preferred over the application
defaults.
addresses #40
=> add parameterization for host and port

.github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/test.yml
For issue #54 
In order to use this code, you need to setup secrets in the repository. Repo settings -> Secrets
`DOCKER_USERNAME`
`DOCKER_PASSWORD`
=> Crossbuild docker image for different architectures

.gitignore, controller/controller.go, storage/memory.go, storage/memory_test.go, watchdog/watchdog.go
The watchdog was responsible for a few things, notably handling the storage of evaluated service health results.
This doesn't _really_ feel like the watchdog's responsibility. Abstracting this behind a storage package feels more suitable, and isolates the storage logic in a single place, also making it testable.
This PR does the above - extracting the in memory store into its own storage package and making the watchdog consume that. This simplifies the code within the watchdog, and also introduces tests for the in memory store. This should also make it easier to extend the storage mechanism without changing the watchdog significantly (for example, adding support for persistent storage as in #32)
After running Gatus with 11 configured services, each evaluating health every 1s for 5 …
=> Split memory map out of watchdog

controller/controller.go
Yielding a 404 error, raised by the handler in the line above
=> fix: metrics were not working

alerting/provider/custom/custom.go, alerting/provider/custom/custom_test.go, config/config_test.go
I am a colleague of GeorgFleig which opened issue #76. This pull request  actually implements this feature in the form it was proposed in https://github.com/TwinProduction/gatus/issues/76#issuecomment-765863720
Would be awesome if it get merged. Feedback welcome.
=> Make ALERT_TRIGGERED_OR_RESOLVED placeholder values configurable

core/condition.go, core/condition_test.go
Fixes #98 - Unsure if this will be a desirable solution or not, but figured I would at least try and contribute a fix!
=> Truncate long strings when using pattern function

README.md, alerting/provider/pagerduty/pagerduty.go, alerting/provider/pagerduty/pagerduty_test.go
Provides support for paging multiple teams based on the `group` selector while keeping backward compatibility to the old pagerduty configuration manifest 
-  integration per team can be specified in the integrations sections in an array form.
```yaml
alerting:
pagerduty: 
integration-key: "00000000000000000000000000000000"
integrations:
- integration-key: "00000000000000000000000000000000"
group: "team"
```
behavior:
- team integration have priority over the general integration (old pagerduty configuration)
- if no team integration is provided it will defaults to the general pagerduty integration 
- if no team integration and no general integration were provided it defaults to the first team integration provided
=> Add group-specific integration key for PagerDuty

LICENSE, LICENSE.md
Call me indecisive if you want, since I've done this once before (see 70c9c4b87c8e595f4374b895853312cefc2152f2), but after thing about the pros and cons, I decided that Apache 2 offers better protection for Gatus.
Long story short:
- **v0.0.1** to **v1.3.0**: Apache 2
- **v1.3.1** to **v3.3.5**: MIT
- **v3.3.6** and up: Apache 2
---
This PR is here for traceability.
=> Change license to Apache 2

alerting/provider/custom/custom.go, alerting/provider/custom/custom_test.go, alerting/provider/discord/discord.go, alerting/provider/mattermost/mattermost.go, alerting/provider/messagebird/messagebird.go, alerting/provider/pagerduty/pagerduty.go, alerting/provider/slack/slack.go, alerting/provider/teams/teams.go, alerting/provider/telegram/telegram.go, alerting/provider/twilio/twilio.go, config/config.go, controller/handler/gzip.go, core/endpoint.go, core/endpoint_test.go, storage/store/memory/memory.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). Since gatus has been upgraded to Go 1.17 in babe7b0be9612271c5a491aa124909af7fc7767b, This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
=> refactor: move from io/ioutil to io and os packages

README.md, alerting/alert/type.go, alerting/config.go, alerting/provider/opsgenie/opsgenie.go, alerting/provider/opsgenie/opsgenie_test.go
New alert provider with [Opsgenie](https://www.atlassian.com/software/opsgenie)
Ref: https://docs.opsgenie.com/docs/alert-api
It turns Gatus able to open and close alerts in [Opsgenie API](https://docs.opsgenie.com/docs/alert-api)
```yml
opsgenie:
api-key: api-key
priority: P1
source: gatus
entity-prefix: gatus-
alias-prefix: gatus-healthcheck-
tags:
- my:extra:tag
````
=> Opsgenie Alert Provider

alerting/alert/alert.go, alerting/alert/alert_test.go, alerting/provider/discord/discord.go, alerting/provider/email/email.go, alerting/provider/mattermost/mattermost.go, alerting/provider/messagebird/messagebird.go, alerting/provider/opsgenie/opsgenie.go, alerting/provider/opsgenie/opsgenie_test.go, alerting/provider/pagerduty/pagerduty.go, alerting/provider/slack/slack.go, alerting/provider/slack/slack_test.go, alerting/provider/teams/teams.go, alerting/provider/telegram/telegram.go, alerting/provider/twilio/twilio.go, core/endpoint.go
closes #199 
closes #220 (sorry for stealing your PR 😅)
This is technically a breaking change, because characters like `"` and `\` can no longer be put in alert descriptions, endpoint groups, and endpoint names.
I have however decided to not make this a breaking change due to how minor the breaking change is and mostly inconsequential outside of a very small subset of users.
=> Add group in alert messages + Validate Name/Group/Description 

README.md, alerting/provider/email/email.go
This is intended to maintain backwards compatibility with using Provider.from.
I am unfamiliar with golang so apologies for any style mistakes
=> Update email alerting provider to supply a username

README.md
At several places throughout the readme document, there appears to be incorrect grammar. 
This PR should fix the problem by correcting all instances of correct grammar in the readme.
`if there’s no traffic that makes it to your applications.` may be considered wordy. 
Replaced with `if no traffic makes it to your applications.`
`not create another incident, but mark the incident ` It appears you have an unnecessary comma in a compound predicate.
Replaced with `not create another incident but mark the incident`
`As a rule of the thumb` It seems there is an article usage problem here.
Replaced with `As a rule of thumb`
`Gatus can automatically generate a SVG badge for one of your monitored endpoints.` The article `a` may be incorrect. Changed to agree with the beginning sound of the word …
=> chore: Fix grammatical issues in README

core/endpoint.go
- Replace all occurences of hostname in errors of result with "host"
- Closes #240
=> fix(config): replace hostname in error string if opted

README.md, alerting/provider/teams/teams.go, alerting/provider/teams/teams_test.go
Add group-specific webhook URL for teams alert
Provides support for paging multiple teams based on the group selector while keeping backward compatibility to the old Teams configuration manifest
integration per team can be specified in the overrides sections in an array form.
```yaml
alerting:
teams:
webhook-url: "https://********.webhook.office.com/webhookb2/************"
overrides:
- group: "core"
webhook-url: "https://********.webhook.office.com/webhookb3/************"
endpoints:
- name: website
url: "https://twin.sh/health"
interval: 30s
conditions:
- "[STATUS] == 200"
- "[BODY].status == UP"
- "[RESPONSE_TIME] < 300"
alerts:
- type: teams
enabled: true
description: "healthcheck failed"
send-on-resolved: true
- name: back-end
group: core
url: "https://example.org/"
interval: 5m …
```
=> feat(alerting): Add group-specific webhook URL for teams

README.md, alerting/provider/googlechat/googlechat.go, alerting/provider/googlechat/googlechat_test.go
Add group-specific webhook URL for Google Chat
```yaml
alerting:
googlechat: 
webhook-url: "https://chat.googleapis.com/v1/spaces/*******/messages?key=**********&token=********"
overrides:
- group: "core"
webhook-url: "https://chat.googleapis.com/v1/spaces/*******/messages?key=**********&token=********"
endpoints:
- name: website
url: "https://twin.sh/health"
interval: 30s
conditions:
- "[STATUS] == 200"
- "[BODY].status == UP"
- "[RESPONSE_TIME] < 300"
alerts:
- type: googlechat
enabled: true
description: "healthcheck failed"
send-on-resolved: true
- name: back-end
group: core
url: "https://example.org/"
interval: 5m
conditions:
- "[STATUS] == 200"
- "[CERTIFICATE_EXPIRATION] > 48h"
alerts:
- type: googlechat
enabled: true
description: "healthcheck failed"
send-on-resolved: true
```
ref: …
=> feat(alerting): Add group-specific WebHook URL for Google Chat

README.md, client/client_test.go, client/config.go
Added a new configuration option to the `client` to allow the user to specify a custom DNS resolver.
Example config:
```yaml
endpoints:
- name: front-end
group: core
url: "https://twin.sh/health"
interval: 30s
client:
dns-resolver: "tcp://1.1.1.1:53"
conditions:
- "[STATUS] == 200"
- "[BODY].status == UP"
- "[RESPONSE_TIME] < 150"
```
=> feat(client): Added client configuration option for using a custom DNS resolver

client/client.go, config/config.go, config/remote/remote.go, controller/controller.go, controller/controller_test.go, controller/handler/badge_test.go, controller/handler/chart_test.go, controller/handler/endpoint_status.go, controller/handler/endpoint_status_test.go, controller/handler/favicon_test.go, controller/handler/handler.go, controller/handler/handler_test.go, controller/handler/spa_test.go, main.go
This is an experimental feature and it may be removed or updated in a breaking manner at any time. Use at your own risk.
Basically, all it does it retrieve the endpoint statuses from another remote host before returning the endpoint statuses. You may specify an endpoint prefix to prefix the name of all endpoints coming from a given remote instance with a string.
```yaml
remote:
instances:
- endpoint-prefix: "myremoteinstance-"
url: "https://status.example.org/api/v1/endpoints/statuses"
```
Relevant: #64
=> feat(remote): Implement lazy distributed feature

README.md, storage/config.go, storage/store/sql/sql.go, storage/store/sql/sql_test.go, storage/store/store.go, storage/store/store_bench_test.go, storage/store/store_test.go
This adds the ability to enable a write-through cache for storage of type sqlite and postgres.
=> feat(storage): Add optional write-through cache to sql store

README.md, core/condition.go, core/endpoint.go, core/endpoint_test.go, core/result.go, go.mod, go.sum, storage/store/sql/specific_postgres.go, storage/store/sql/specific_sqlite.go, storage/store/sql/sql.go, vendor/github.com/TwiN/whois/.gitignore, vendor/github.com/TwiN/whois/LICENSE, vendor/github.com/TwiN/whois/Makefile, vendor/github.com/TwiN/whois/README.md, vendor/github.com/TwiN/whois/whois.go, vendor/modules.txt
Closes #133
This feature allows users to monitor domain expiration by leveraging the WHOIS protocol through the [TwiN/whois](https://github.com/TwiN/whois) library.
Here's an example of what an endpoint configured to monitor
```yaml
endpoints:
- name: check-domain-expiration
url: "https://example.org"
interval: 1h
conditions:
- "[DOMAIN_EXPIRATION] > 720h"
```
=> feat: Add [DOMAIN_EXPIRATION] placeholder for monitoring domain expiration using WHOIS

README.md, alerting/provider/telegram/telegram.go
Adds an option to specify the client config for the telegram alerting provider.
I'm monitoring a local dns server, so the notifications should still go through if the local dns is down.
Builds on top of #284 
I have to admit I have never worked with Go before, so I'm not sure how to compile and test the project, but this change seems relatively straighforward.
=> feat(alerting): add client config for telegram

README.md, alerting/alert/type.go, alerting/config.go, alerting/provider/ntfy/ntfy.go, alerting/provider/ntfy/ntfy_test.go, alerting/provider/provider.go, alerting/provider/slack/slack_test.go, config/config.go
Closes https://github.com/TwiN/gatus/issues/308
Work remaining:
=> feat(alerting): Implement ntfy provider

config/config.go
Related to #234.
It seems like this was missed in the PR, rendering Google Chat alerts not working.
=> fix: add Google Chat to list of alert types when determining valid providers

core/condition_test.go, jsonpath/jsonpath.go, jsonpath/jsonpath_test.go
=> fix: Make sure len([BODY]) works if the body is a JSON array

README.md, client/client.go, core/endpoint.go, core/endpoint_test.go, go.mod, go.sum, vendor/github.com/ishidawataru/sctp/.gitignore, vendor/github.com/ishidawataru/sctp/.travis.yml, vendor/github.com/ishidawataru/sctp/GO_LICENSE, vendor/github.com/ishidawataru/sctp/LICENSE, vendor/github.com/ishidawataru/sctp/NOTICE, vendor/github.com/ishidawataru/sctp/README.md, vendor/github.com/ishidawataru/sctp/ipsock_linux.go, vendor/github.com/ishidawataru/sctp/sctp.go, vendor/github.com/ishidawataru/sctp/sctp_linux.go, vendor/github.com/ishidawataru/sctp/sctp_unsupported.go, vendor/modules.txt
Related Issue: https://github.com/TwiN/gatus/issues/333
I added the handlers on sctp and udp protocol.
Cause I want to use gatus to monitor all the interfaces on 5G core network.
=> feat: support SCTP & UDP as endpoint type

alerting/config.go, alerting/provider/googlechat/googlechat.go, alerting/provider/googlechat/googlechat_test.go
=> fix(alerting): Resolve GoogleChat bad payload issue

.examples/docker-compose-mattermost/config/config.yaml, README.md, alerting/alert/alert.go, alerting/alert/alert_test.go, config/config_test.go, core/endpoint_test.go
BREAKING CHANGE: It used to default to false, which meant that users had to explicitly set endpoints[].alerts[].enabled to true
Discussion #374
=> fix!: Default Alert.Enabled to true

config/config.go, config/config_test.go
BREAKING CHANGE: `services` has been replaced by `endpoints` in v3.3.0, but backward compatibility has been retained until now. v5.0.0, however, will no longer support `services`, so make sure to update your configuration to use `endpoints` instead.
See #374 for more information
=> chore!: Remove deprecated "services" in favor of "endpoints"

core/condition.go, core/condition_test.go, core/endpoint.go, core/endpoint_test.go
BREAKING CHANGE: The comparator in each condition must now be wrapped by a space (e.g. [STATUS] == 200) or the condition will not be valid.
=> fix!: Enforce mandatory space around condition operator

alerting/config.go, config/config.go, config/config_test.go, watchdog/alerting.go
Instead of re-validating the corresponding alerting provider of an alert every time said alert is triggered/resolved, use reflection to set the alerting configuration's provider field to nil
=> fix(alerting): Use reflection to set invalid providers to nil instead of re-validating on every alert trigger/resolve

core/condition_test.go, jsonpath/jsonpath.go
=> fix: Prevent jsonpath from causing panic when body is expected to be array but isn't

README.md, config/config.go, config/config_test.go, main.go, test-conf/conf.d/endpoints.yaml, test-conf/conf.d/endpoints.yml, test-conf/config.yaml
This PR allows configuration to split across multiple files using the common `config.d/`-path style. The approach reads all `*.yml` and `*.yaml` files and merges them in memory into a single file before parsing.  This seemed easier und required fewer changes than parsing each file individually and merging the objects afterwards.
Fixes #326
As I did not work with golang before, feel free to remark on obvious errors and bad patterns.
I envisaged to write tests, but did not figure out yet, how invasive tests are intended to be structured for this project. I hope the chosen way is in you interest.
=> feat: Support multiple configuration files

README.md, alerting/alert/type.go, alerting/config.go, alerting/provider/provider.go, alerting/provider/pushover/pushover.go, alerting/provider/pushover/pushover_test.go, config/config.go, config/config_test.go, watchdog/alerting_test.go
I am not sure if I missed something. There are a lot of files where providers are referenced, but I think I got all of them.
- Adds new provider named Pushover with corresponding tests
- Adds Pushover as a provider to the configuration and adjusts test accordingly
- Adds Pushover to alerting_test.go, provider.go and type.go
- Updates the readme with configuration details
Before merging: what would be the best way to properly test this with real API calls? Is there any process defined or should I just try to build it and check if a config works?
Additional thoughts/ideas that could be implemented later:
- Add support for other configuration options, like device support, the Gatus URL in it or setting a sound
- Allow overriding of title, priority,... per group like the PagerDuty provider …
=> feat(alerting): Add Pushover provider

storage/store/sql/sql_test.go
Fixes #388 (flaky TestStore_InsertCleansUpOldUptimeEntriesProperly)
- [ X] Tested and/or added tests to validate that the changes work as intended, if applicable.
=> fix(test): flaky TestStore_InsertCleansUpOldUptimeEntriesProperly

README.md, alerting/provider/pushover/pushover.go, alerting/provider/pushover/pushover_test.go
In  extension to #405 (#129) this PR adds support to configure sound for Pushover.
https://pushover.net/api#sounds
=> feat(alerting): Add Pushover sound support

README.md, core/condition.go, core/condition_test.go, jsonpath/jsonpath_test.go
Fixes https://github.com/TwiN/gatus/issues/433
Does not add support for decimal numbers, but it converts float64 to int64.
The reason why I'm not just using float64 instead of int64 is because float64 does not support all the numbers that int64 supports, which means this would be a breaking change. Instead, this change at least supports the non-decimal part of floating point numbers.
This is an improvement over the current implementation, as right now, numbers with decimals are just converted to 0 when compared using a non-equal operator
=> fix(condition): Partially support numbers with floating point

README.md, client/client_test.go, config/config.go, config/connectivity/connectivity.go, config/connectivity/connectivity_test.go, watchdog/watchdog.go
While Gatus is used to monitor other services, it is possible for Gatus itself to lose connectivity to the internet.
In order to prevent Gatus from reporting endpoints as unhealthy when Gatus itself is unhealthy, you may configure 
Gatus to periodically check for internet connectivity.
All endpoint executions are skipped while the connectivity checker deems connectivity to be down.
=> feat(connectivity): Allow internet connection validation prior to endpoint execution

README.md, alerting/provider/ntfy/ntfy.go, alerting/provider/ntfy/ntfy_test.go
Hi, I hope I got everything right. Let me know if I need to fix something before this can be merged.
I've added the ability to use [access tokens](https://docs.ntfy.sh/publish/#access-tokens) in the ntfy alert module.
This _should_ fix #419, though I have not implemented user-password based auth. Ntfy makes it really simple to use tokens, so I did not want to complicate the code any more than necessary. (And I'm lazy.)
=> feat(alerting): Add token authorization for ntfy

web/app/src/components/EndpointGroup.vue
Hi, Gatus is awesome.
I implemented a simple change to show a number of failing checks instead of just an icon.
Please let me know if interested; then I'll finish the tests, etc.
=> feat(ui): Show number of failing checks per group

README.md, config/web/web.go, config/web/web_test.go, controller/controller.go
=> fix(tls): Pass certificate and private key files to listener method

alerting/provider/telegram/telegram.go, alerting/provider/telegram/telegram_test.go
There is a typo in Telegram alerting provider implementation: for resolved alerts, instead of success count, failure count is printed instead.
This PR fixes the typo and adjusts relevant test cases.
=> fix(alerting): correct success threshold for telegram

.github/workflows/publish-latest-to-ghcr.yml, .github/workflows/publish-latest.yml
Otherwise, the workflow will attempt to publish on forks from contributors that are using the master branch
=> ci: Publish only if the workflow is not running on a fork

.examples/docker-compose-postgres-storage/config/config.yaml, .examples/docker-compose-postgres-storage/docker-compose.yml, README.md
The example for Postgres shows the database credentials in plain text in `config.yaml`, which isn't an ideal way to provide credentials. I didn't initaly realise environment variables could be used in config files until I saw #75 . I later noticed the note in the README. Hopefully this makes it clearer and provides a better example for configuring database connections.
=> docs: demonstrate use of environment variables in config

README.md, client/client.go, client/client_test.go, client/config.go
This PR adds support to explicitly specify the network to use for ICMP endpoint clients, e.g. IPv6.
In the future, this may be extended to also support HTTPS endpoints (requested https://github.com/TwiN/gatus/issues/185).
I decided to use `ping.NewPinger` instead of `ping.New`, because the latter automatically [resolves](https://github.com/prometheus-community/pro-bing/blob/6bee2459eb4c8ab44f90837a700ae8e1dc0e035c/ping.go#L336) the address before we can set the desired network.
I set `ip` as the default config value. This is technically not needed and could be an empty string, because [`SetNetwork`](https://github.com/prometheus-community/pro-bing/blob/6bee2459eb4c8ab44f90837a700ae8e1dc0e035c/ping.go#L374) takes care of it anyways, but I think it's a cleaner approach.
I am running Gatus …
=> feat(client): Add client network configuration for ICMP endpoint clients

README.md, api/api.go, config/web/web.go, config/web/web_test.go
This fixes the `431 Request Header Fields Too Large` error
By default, the read-buffer-size is 8192, up from fiber's default of 4096.
Fixes #674
Fixes #636
Supersedes #637
Supersedes #663
=> fix(web): Allow configuration of read-buffer-size

alerting/config.go, alerting/provider/awsses/awsses.go, alerting/provider/pagerduty/pagerduty.go, api/chart.go, api/endpoint_status.go, api/spa.go, client/config.go, config/config.go, controller/controller.go, core/condition.go, core/endpoint.go, core/endpoint_test.go, main.go, security/config.go, security/oidc.go, storage/store/sql/sql.go, storage/store/store.go, watchdog/alerting.go, watchdog/watchdog.go
Clean up code and change log format
=> refactor: Clean up code and change log format

alerting/alert/alert.go, alerting/alert/alert_test.go, api/external_endpoint_test.go, config/config.go, config/config_test.go, main.go, storage/store/memory/memory.go, storage/store/sql/specific_postgres.go, storage/store/sql/specific_sqlite.go, storage/store/sql/sql.go, storage/store/sql/sql_test.go, storage/store/store.go, watchdog/alerting.go
=> feat(alerting): Persist triggered alerts across application restart

.github/workflows/publish-latest-to-ghcr.yml, .github/workflows/publish-latest.yml, .github/workflows/publish-release-to-ghcr.yml, .github/workflows/publish-release.yml
Drops support for linux/arm/v6
This slows down publish workflows quite a bit, and armv6 is pretty old anyways.
=> build: Drop support for linux/arm/v6

README.md, alerting/provider/telegram/telegram.go, alerting/provider/telegram/telegram_test.go
#717 
Add feat with overriding of telegram token and id for specific groups.
=> feat(alerting): add telegram overriding token and id

README.md, api/badge.go, api/chart.go, api/chart_test.go, storage/store/memory/uptime.go, storage/store/memory/uptime_test.go, storage/store/sql/sql.go, storage/store/sql/sql_test.go
Add support for 30d uptime badges, response time badges and response time chart.
Resolves #128
Resolves #714
=> feat(storage): Support 30d badges

README.md, alerting/alert/type.go, alerting/config.go, alerting/provider/provider.go, alerting/provider/zulip/zulip.go, alerting/provider/zulip/zulip_test.go, config/config.go
=> feat(alerting): Implement Zulip's alerts

README.md, alerting/provider/ntfy/ntfy.go, alerting/provider/ntfy/ntfy_test.go
Adds the email and click properties to the ntfy provider.
- email - will optionally send the notification also to this email
- click - will optionally add a link to the notification to be clicked on (e.g., a link to the gatus instance)
Documentation to publishing on ntfy via JSON:  https://docs.ntfy.sh/publish/#publish-as-json
Edit: Now also adds the properties [`firebase`](https://docs.ntfy.sh/publish/#disable-firebase) and [`cache`](https://docs.ntfy.sh/publish/#message-caching), which currently cannot be defined in JSON but as http headers (https://github.com/binwiederhier/ntfy/issues/1119).
- manually tested configurations with and without these properties
=> feat(alerting): add email and click action to ntfy provider

README.md
I changed the url of the Helm Chart in the README.md to your own repo.
=> docs: change the url of the helm chart to your repo

alerting/alert/type.go, config/config.go
I noticed some weird behaviour where I wasn't getting alert resolved notifications through the new teams-workflows provider, while other alerting providers were working with the same config.
I went spelunking and while doing so, noticed teams-workflows was missing from the configuredProviders list at startup, even though it was sending alerts. This led me on the path to making the changes in the PR, which seem to have resolved the default-alerts issue.
Example config where aws-ses was working, while teams-workflow was not.
```yaml
alerting:
teams-workflows:
webhook-url: "xxx"
default-alert:
description: "healthcheck failed 3 times in a row"
send-on-resolved: true
aws-ses:
region: "xxx"
from: "xxx"
to: "xxx"
default-alert:
description: "healthcheck failed 3 times in a row" …
```
=> fix(alerting): Add missing support for default-alert on teams-workflows

.examples/docker-compose-multiple-config-files/config/global.yaml, .github/workflows/benchmark.yml, .github/workflows/test.yml, Dockerfile, README.md, alerting/config.go, alerting/provider/pagerduty/pagerduty.go, api/api.go, api/chart.go, api/endpoint_status.go, api/external_endpoint.go, api/spa.go, client/client.go, client/config.go, config/config.go, config/config_test.go, config/endpoint/condition.go, config/remote/remote.go, controller/controller.go, go.mod, go.sum, main.go, security/config.go, security/oidc.go, storage/store/sql/sql.go, storage/store/store.go, watchdog/alerting.go, watchdog/alerting_test.go, watchdog/watchdog.go
Replace log-level parameter by GATUS_LOG_LEVEL env var
Tweaks implementation of logging levels in #872
=> fix(logging): Replace log-level parameter by GATUS_LOG_LEVEL env var

alerting/provider/teamsworkflows/teamsworkflows.go, alerting/provider/teamsworkflows/teamsworkflows_test.go
I've updated the design of the adaptive card for msteams as follows:
- Stretch card to entire width
- Add a colored border signaling success or error
New Design examples:
=> feat(alerting): Update Adaptive Cards design for teams-workflows

README.md
Some of the text examples used `proto:\\` instead of `proto://`. The backslash is not correct and results in "panic: invalid endpoint testgroup-|-testendpoint: unknown endpoint type".
NA
=> docs: Change protocol backslash (\\) to forwardslash (//) in README.md

client/client_test.go
adds tests to complement work done in
https://github.com/TwiN/gatus/pull/547
it was rumored that tls insecure was not working,
although tls insecure appears to be working fine,
no test was found originally.
this adds a test to ensure that tls insecure works as expected. the domain badssl.com is used to
verify that the insecure flag works as expected
address issue https://github.com/TwiN/gatus/issues/932
=> test(client): add test for insecure flag

client/client_test.go, config/endpoint/endpoint_test.go
Fix flaky DNS tests that check for valid IP
=> test: Fix flaky DNS tests that check for valid IP

README.md, metrics/metrics.go, metrics/metrics_test.go
=> feat(metrics): add `gatus_results_endpoint_success`

config/maintenance/maintenance.go, config/maintenance/maintenance_test.go
Fixes an issue with the timezone handling in Maintenance blocks
https://github.com/TwiN/gatus/issues/911
The problem was with using Truncate, which always operates in UTC. Switching to constructing the date from component parts (`0, 0, 0, 0` for midnight) fixes this issue and makes the time always midnight for the timezone the maintenance window refers to.
I've added a test for this too - the previous test didn't catch the problem because it was only an hour out from UTC, and the window covered a 2 hour period. I've using UTC+8 (Australia/Perth) for a large enough gap to catch the issue. This test fails without the code changes, and passes now.
=> fix(maintenance): timezone handling offset issue

storage/store/store.go, watchdog/watchdog.go
- Use `time.Ticker` instead of `time.After` for periodic operations in `autoSave` function
- Use `time.Ticker` instead of `time.After` for periodic operations in `monitor` function
This PR includes the following changes:
* Replaced `time.After(interval)` with `time.NewTicker(interval)` in both storage/store/store.go and watchdog/watchdog.go.
* This change ensures that the automatic save and monitoring operations are executed regularly and that the ticker is properly stopped when the context is done.
=> refactor: periodic operations to use `time.Ticker`

config/config.go
Ignore config files with double dot in it, permit to mount Kubernetes ConfigMap as directory and ignore hidden files like `..date/filename.yaml`.
=> fix(config): Ignore config files with double dot in it (#696)

README.md, alerting/alert/type.go, alerting/config.go, alerting/provider/incidentio/incident_io.go, alerting/provider/incidentio/incident_io_test.go, alerting/provider/provider.go, config/config.go
- Added Incident.io as an alerting provider.
- Added testing for Incident.io alerting provider.
- Added documentation.
Fixes #967
=> feat(alerting): Add Incident.io alerting provider

config/endpoint/endpoint.go
Fixes #1042
See https://github.com/TwiN/gatus/issues/1042#issuecomment-2755892843 for explanation
=> fix(client): Correctly parse hostname for ICMP endpoint when using IPv6

Dockerfile
Fixes #697
This PR modifies the Gatus binary in the container to have the CAP_NET_RAW capability.  Gatus can now perform ICMP monitoring without running as a privileged or root container.
=> fix(client): Use libcap to fix icmp not working in containers as non-root

README.md, api/api.go, api/raw.go, api/raw_test.go
Fixes #1069 
This adds an endpoint int the api to retrieve raw response times
=> feat(api): Add endpoint to retrieve response time

README.md, alerting/provider/pushover/pushover.go, alerting/provider/pushover/pushover_test.go
Closes #1090
The current Pushover provider does not allow targeting a specific device—Pushover itself supports this via an optional device parameter. This PR adds support for the device field in Gatus so users can send alerts to a single device rather than all registered devices.
=> feat(alerting): Add device support for pushover alerts

alerting/provider/custom/custom.go, alerting/provider/custom/custom_test.go
This is my first PR so probably might be missing some detail
https://github.com/TwiN/gatus/issues/951
Escape `"`  in the result errors
=> fix(alerting): Escape custom result errors

README.md
The hash was missing.
This aligns the docs with the implementation
https://github.com/TwiN/gatus/blob/b388cc87aa30fcfb83601a32c40a49286cc7374d/config/endpoint/key.go#L10-L19
=> docs: Update list of characters sanitised in endpoint key

api/util.go
Limit the pageSize to maximum-number-of-results on first page
=> fix: Limit the pageSize to maximum-number-of-results on first page

README.md, client/client.go, client/client_test.go, config/endpoint/endpoint.go
Add support for custom HTTP headers (including `User-Agent`) to WebSocket (`ws://` and `wss://`) checks. Headers defined in the endpoint config are now injected into the WebSocket handshake, just like in HTTP checks.
Out of the box, WebSocket checks did not include any HTTP headers in their upgrade handshake. This caused real-world issues such as requests being blocked by WAFs with rules like `NoUserAgent`, making monitoring unreliable for protected endpoints.
Additionally, allowing user-defined headers (e.g., `Authorization`, custom tracing headers, etc.) significantly expands observability and flexibility for WebSocket-based services by enabling authentication, routing, or identification during the handshake.
=> feat(websocket): add support for custom headers in WS check

alerting/provider/provider.go, alerting/provider/provider_test.go
Fixes #379
I had tried this and it wasn't working:
```
alerting:
slack:
webhook-url: xyz
default-alert:
description: "Health Check"
send-on-resolved: true
failure-threshold: 2
success-threshold: 2
minimum-reminder-interval: 48h
```
It does work if you put it with each endpoint specifically though
=> fix(alerting): Adjust minimum reminder config parsing

README.md, config/config.go, config/config_test.go, security/config.go, security/config_test.go, security/oidc.go, security/oidc_test.go
Fixes #1279
This also increases the default OIDC session TTL from 1h to 8h
=> fix(security): Make OIDC session TTL configurable
