README.md, core/alert.go, core/alerting.go, watchdog/watchdog.go
I couldn't quite make this work with a custom alert type, so added it as a new type
=> Add Twilio SMS alerts

static/index.html
Added code to change the refresh interval.
Some UI change might need to be made, but functionality is there.
#1
=> Add support for refresh interval

README.md, config/config.go, config/config_test.go, main.go, security/handler.go, security/handler_test.go, security/security.go, security/security_test.go, security/sha512.go, security/sha512_test.go
=> Implement basic authentication for dashboard

README.md, core/condition.go, core/condition_test.go
=> Add basic duration comparison

README.md, alerting/config.go, alerting/provider/custom/custom.go, alerting/provider/mattermost/mattermost.go, alerting/provider/messagebird/messagebird.go, alerting/provider/messagebird/messagebird_test.go, alerting/provider/provider.go, alerting/provider/slack/slack.go, alerting/provider/twilio/twilio.go, config/config.go, config/config_test.go, core/alert.go
PR adds support for messagebird alerting by sending an SMS message. I have tested it before creating the PR 🙂
=> Add Messagebird alerting

client/client.go
Closes https://github.com/TwinProduction/gatus/issues/86
=> Respect system proxy

README.md
Quite by accident while poking around in the code I found the API capabilities, and they're not documented at all.
This PR adds some simple notes around the API and it's usage.
=> Add API capabilities to docs

README.md, alerting/provider/custom/custom.go, alerting/provider/discord/discord.go, alerting/provider/mattermost/mattermost.go, alerting/provider/messagebird/messagebird.go, alerting/provider/pagerduty/pagerduty.go, alerting/provider/provider.go, alerting/provider/provider_test.go, alerting/provider/slack/slack.go, alerting/provider/telegram/telegram.go, alerting/provider/telegram/telegram_test.go, alerting/provider/twilio/twilio.go, alerting/provider/twilio/twilio_test.go, config/config.go, config/config_test.go, core/alert.go, core/alert_test.go, core/service.go, core/service_test.go, jsonpath/jsonpath.go, jsonpath/jsonpath_test.go, watchdog/alerting.go, watchdog/alerting_test.go
=> Implement default provider alert

client/client.go, client/client_test.go, config.yaml, core/service.go
Hello,
Thank you for your great tool. I wanted to test some SMTP servers so I added a few lines of codes.
Regards.
GJ
=> Add support for StartTLS protocol

README.md
Closes https://github.com/avakarev/gatus-chart/issues/17
Here is [markdown preview](https://github.com/avakarev/gatus/tree/document-helm-chart#helm-chart)
=> Document helm chart

README.md, alerting/provider/custom/custom.go, alerting/provider/mattermost/mattermost.go, client/client.go, client/client_test.go, client/config.go, client/config_test.go, config/config_test.go, controller/controller_test.go, core/service.go, core/service_test.go
=> Add client configuration

README.md, client/client.go, client/client_test.go, core/service.go
- Add SSL service health check;
- Add timeout feature for StartTLS checks.
=> Health check for SSL/TLS services

README.md
Add maintenance to root config table on README to avoid confusion.
#222
=> Changed: add maintenance to README on root config table

.github/workflows/publish-latest.yml
Redo of #237, fixed typo with a rebase oops.
=> build(docker): support all platforms that publish release supports

README.md, alerting/provider/telegram/telegram.go
=> add config option for a custom telegram api

README.md
=> docs(cert): list valid units for CERTIFICATE_EXPIRATION

client/client_test.go, client/config.go, client/config_test.go, controller/handler/endpoint_status_test.go, core/endpoint.go, core/endpoint_test.go, storage/store/memory/memory_test.go, storage/store/sql/sql.go, storage/store/sql/sql_test.go, storage/store/store_bench_test.go, storage/store/store_test.go
Improved benchmarks & cleaned up some code
=> perf(storage): Improve benchmarks and fix race condition

README.md, alerting/provider/mattermost/mattermost.go, alerting/provider/mattermost/mattermost_test.go
This PR adds the the override option for the Mattermost alert integration.
=> feat(alerting): Add overrides for Mattermost

core/dns_test.go, core/result.go, metrics/metrics.go, metrics/metrics_test.go, vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go, vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go, vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go, vendor/modules.txt, watchdog/watchdog.go
This PR adds tests for metrics
=> Add tests for metrics

README.md, config/config.go, controller/handler/badge.go, controller/handler/badge_test.go, controller/handler/handler.go, core/endpoint.go, core/ui/ui.go
view original pull request for more information #267
=> feat(api): Configurable response time badge thresholds

go.mod, go.sum, storage/store/memory/memory.go, storage/store/memory/memory_test.go, storage/store/store.go, storage/store/store_bench_test.go, storage/store/store_test.go, vendor/github.com/TwiN/gocache/v2/LICENSE.md, vendor/github.com/TwiN/gocache/v2/README.md, vendor/github.com/TwiN/gocache/v2/gocache.go, vendor/modules.txt
Persistence for the memory store has been removed in v4.0.0, so there's no need to keep the code around any longer.
=> refactor(storage): Remove decommissioned path for memory store

jsonpath/jsonpath.go, jsonpath/jsonpath_bench_test.go, jsonpath/jsonpath_test.go
=> perf: Improve jsonpath speed

README.md
Relevant discussion: https://github.com/TwiN/gatus/discussions/370
=> Clarify description of `len()` function

config/config.go, config/config_test.go
This allows escaping `$` in the configuration file by prefixing it with another `$` (i.e. to escape a dollar sign, users have to use `$$`).
Example:
```yaml
endpoints:
- name: example
url: https://example.org/docs/how-to-create-config-file-without-including-literal-password-in-it
conditions:
- "[BODY] == pat(*$$PASSWORD*)"
```
(for verbosity, the above endpoint assumes that there's `$PASSWORD` in the body)
Fixes #422
=> fix(config): Support `$$` in config for literal `$`

README.md
This PR corrects a small typo in the docs
=> docs(alerting): Correct newline in docu

README.md
=> Helm chart moved from avakarev/gatus-chart to minicloudlabs/helm-charts

alerting/provider/email/email.go, alerting/provider/email/email_test.go
=> fix(alerting): use same email subject for trigger and resolution alert

config/maintenance/maintenance.go, config/maintenance/maintenance_test.go
=> fix(alerting): Unable to set maintenance interval to all day

README.md
Added FAQ to address issue https://github.com/TwiN/gatus/issues/88.
=> docs: Specify that exposing Gatus through a subpath is not supported

README.md, core/endpoint.go
- handle error returned from websocket connection
- fix typo on readme
=> websocket: handle error

alerting/provider/email/email.go, alerting/provider/email/email_test.go
=> fix(alerting): Set correct email subject to resolved alert

.github/workflows/publish-latest-to-ghcr.yml, .github/workflows/publish-latest.yml
=> ci: Tweak concurrency group key

.github/workflows/publish-latest-to-ghcr.yml, .github/workflows/publish-latest.yml
=> ci: Fix fork conditional

alerting/provider/ntfy/ntfy.go, alerting/provider/ntfy/ntfy_test.go
show the condition results in ntfy notifications like below.
=> fix(alerting): add condition results to ntfy

README.md
=> docs: add instruction to install as binary

Makefile, README.md
- Remove `test` from `.PHONY` and add `install`, `run`, and `clean` targets to `.PHONY`
- Replace build command to include verbose flag and remove `-mod vendor` option
=> build: refine Makefile targets and build command

config/maintenance/maintenance.go
=> fix(maintenance): Import time/tzdata to support timezones

README.md, alerting/provider/ntfy/ntfy.go, alerting/provider/ntfy/ntfy_test.go
Add group overrides to Ntfy alert provider (context: https://github.com/TwiN/gatus/issues/96)
=> feat(alerting): Add overrides for Ntfy provider

metrics/metrics.go, metrics/metrics_test.go
=> Revert "feat(metrics): Add URL to metrics labels"

api/endpoint_status.go
Modified `getEndpointStatusesFromRemoteInstances` function to handle failures gracefully when fetching statuses from remote instances. Previously, if one remote endpoint was unavailable, it would fail to show all remotes in the UI.
Key changes:
- Added error handling to continue processing other instances when one fails
- Added error logging for failed HTTP requests and JSON decoding
- Changed error return behavior to only return error if ALL remote instances fail
- Improved error logging messages to identify which specific remote instance failed
This change makes the system more resilient by:
- Continuing to show statuses from working remote endpoints even if some are down
- Providing better visibility into which specific remote endpoints are failing through logs
- Maintaining overall …
=> fix(remote): Support partial remote instance failure

.github/workflows/test-ui.yml, Makefile, web/README.md
Add workflow to test UI changes
=> ci: Add workflow to test UI changes

client/client.go
=> feat(dns): Support SRV query type

.github/workflows/labeler.yml
=> ci: Add labeler workflow

README.md
https://github.com/TwiN/gatus/issues/1016
=> docs: Clarify that disable-monitoring-lock is akin to enabling parallel execution

README.md, config/endpoint/endpoint.go, config/endpoint/endpoint_test.go, config/endpoint/result.go, config/endpoint/ui/ui.go
Implements new `endpoints[].ui.hide-port` configuration parameter.
Fixes #1036
=> feat(ui): Implement ability to hide port from endpoint results via `endpoints[].ui.hide-port`

storage/store/sql/specific_sqlite.go
Adds indices to sqlite tables. see https://github.com/TwiN/gatus/discussions/1102
=> perf(sqlite): Create indices to fix performance issue

Dockerfile
This reverts #1056
Fixes #1126
=> revert: fix(client): Use libcap to fix icmp

.examples/nixos/README.md, .examples/nixos/gatus.nix
Last year I contributed the Gatus module to NixOS, but realized this is nowhere mentioned on the Gatus project itself. So here!
=> docs: Add NixOS example

config/config.go
Convert key to lowercase when looking up endpoint by key
=> fix: Convert key to lowercase when looking up endpoint by key

.examples/docker-compose-grafana-prometheus/grafana/provisioning/dashboards/gatus.json
Hi there, I created this Grafana Dashboard for Gatus that I thought might also be useful to contribute back:
- [ x ] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [ x ] Updated documentation in `README.md`, if applicable.
=> docs: Update example Grafana dashboard

README.md, api/external_endpoint.go, config/endpoint/external_endpoint.go, config/endpoint/heartbeat/heartbeat.go, storage/store/memory/memory.go, storage/store/memory/memory_test.go, storage/store/sql/sql.go, storage/store/sql/sql_test.go, storage/store/store.go, watchdog/watchdog.go
Fixes #741
Implement heartbeat for external endpoints
=> feat(external-endpoint): Implement heartbeat

README.md
I am excited to use https://github.com/TwiN/gatus/pull/1138 and had to do a little searching to understand what to set this to, I believe this is correct?
=> docs: Add example for alerts[].minimum-reminder-interval

README.md
=> docs: Add section for gatus-sdk

README.md
Improve documentation of `alerts[].minimum-reminder-interval`, cf. https://github.com/TwiN/gatus/pull/1138/.
=> docs: tweak `minimum-reminder-interval` description

README.md
Updated typo in documentation
(CTRL+F on "discord" returned results for zulip config section)
- [] Tested and/or added tests to validate that the changes work as intended, if applicable.
=> docs: Fix typo in Zulip configuration section

config/endpoint/endpoint.go, config/endpoint/endpoint_test.go, config/suite/suite.go, config/suite/suite_test.go
Handle invalid paths in store and update needsToReadBody to check store
=> fix(suites): Handle invalid paths in store and update needsToReadBody to check store

README.md
SIGNL4 warning removed. I have tested it and both, triggering and resolving of alerts work fine.
=> docs(alerting): Remove SIGNL4 untested warning

config/tunneling/sshtunnel/sshtunnel.go
=> fix(tunneling): Add exponential backoff retry
